var express = require("express");
var router = express.Router();

router.use(require("./auth.routes"));
router.use(require("./leads.routes"));
router.use(require("./roles.routes"));
router.use(require("./contract.routes"));
router.use(require("./workOrder.routes"));
router.use(require("./notes.routes"));
router.use(require("./activities.routes"));
router.use(require("./catalog.routes"));
router.use(require("./manufacturer.routes"));
router.use(require("./material.routes"));
router.use(require("./attributes.routes"));
router.use(require("./configureAttribute.routes"));
router.use(require("./productAttribute.routes"));
router.use(require("./productCategory.routes"));
router.use(require("./inventory.routes"));
router.use(require("./applyWorkOrder.routes"));
router.use(require("./customer.routes"));
router.use(require("./project.routes"));
router.use(require("./takeOffQuote.routes"));
router.use(require("./chat.routes"));
router.use(require("./brands.routes"));

router.use(require("./units.routes"));
router.use(require("./vendor.routes"));
router.use(require("./productCategories.routes"));
router.use(require("./tags.routes"));
router.use(require("./item.routes"));
router.use(require("./company.routes"));
router.use(require("./saleMaterialQuotes.routes"));
router.use(require("./companyType.routes"));
router.use(require("./warehouse.routes"));
router.use(require("./taxes.routes"));
router.use(require("./serviceTypeItem.routes"));
router.use(require("./warehouseItems.routes"));
router.use(require("./departments.routes"));
router.use(require("./leadStatuses.routes"));
router.use(require("./leadTypes.routes"));
router.use(require("./leadTags.routes"));
router.use(require("./projectTypes.routes"));
router.use(require("./tickets.routes"));
router.use(require("./leadTeams.routes"));
router.use(require("./termsCodes.routes"));
router.use(require("./interactionTypes.routes"));
router.use(require("./budgetKeyAreas.routes"));
router.use(require("./contacts.routes"));
router.use(require("./productTags.routes"));

module.exports = router;
